import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

import 'tables.dart';

part 'app_database.g.dart'; // generated by build_runner — see NOTE below

/// The single source of truth for local storage. Everything is on-device
/// sqlite; nothing here ever touches the network, matching the "fully
/// local" requirement.
///
/// NOTE ON CODE GENERATION: `app_database.g.dart` (the `part` above) is
/// NOT included in this scaffold — it's generated by running, on your own
/// machine with the Flutter SDK installed:
///
///   dart run build_runner build --delete-conflicting-outputs
///
/// That command reads the @DriftDatabase annotation below and writes the
/// generated row/companion classes (MedicationRow, DoseRow, etc.) used
/// throughout the data layer. Re-run it any time you change tables.dart.
@DriftDatabase(tables: [Medications, Doses])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  // Bump this and add a MigrationStrategy when you change tables.dart
  // after the app has already shipped with real user data.
  @override
  int get schemaVersion => 1;
}

LazyDatabase _openConnection() {
  // Deferred so the actual file I/O only happens when first queried —
  // keeps app startup non-blocking.
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'medication_tracker.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}
